bord/urls.py
from django.conf.urls import url

from .views import (
    BordListView,
    BordDetailView,
    BordCreateView,
    BordUpdateView,
    BordDeleteView,
)

urlpatterns = [
    url(r'^check/(?P<check>\d+)/$', BordListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$',BordDetailView.as_view(), name='detail'),
    url(r'^create/(?P<check>\d+)/$',BordCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$',BordUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',BordDeleteView.as_view(), name='delete'),
]

contact/urls.py
from django.conf.urls import url

from .views import ContactCreateView, ContactDoneView

urlpatterns = [
    url(r'^create/$',ContactCreateView.as_view(), name='create'),
    url(r'^done/$',ContactDoneView.as_view(), name='done')
]

source/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from .views import Home
from .views import UsercreateView , UserCreateDoneView

from django.conf import settings
from django.conf.urls.static import url,static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view()),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UsercreateView.as_view(), name='register'),
    url(r'^accounts/register/done', UserCreateDoneView.as_view(), name='register_done' ),
    url(r'^bord/', include('bord.urls', namespace='bord')),
    url(r'^contact/', include('contact.urls', namespace='contact')),

]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bord/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.
class Bord(models.Model):
    check = models.IntegerField(default=0)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to='bord/%Y/%m')
    description = models.TextField('Bord Description', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, null=True)
    embed_code = models.TextField(null=True)  # 기존값 # 비디오 코드

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bord:detail', args=(self.id,))

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

bord/forms.py
from django import forms

from .models import Bord

class BordForm(forms.ModelForm):
    class Meta:
        model = Bord
        fields = [ 'check','title','image','description','embed_code']

contact/forms.py
from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'message'
        ]

bord/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

import json

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Bord
from .forms import BordForm
# Create your views here.

class BordListView(ListView):
    model = Bord
    template_name = 'bord/bord_list.html'
    paginate_by = 2

    def get_context_data(self, *args,  **kwargs):
        context = super(BordListView, self).get_context_data(**kwargs)
        check = self.kwargs.get('check')
        context['object_list'] = Bord.objects.filter(check = check)
        context['check'] = self.kwargs.get('check')
        return context


class BordDetailView(DetailView):
    model = Bord
    template_name = 'bord/bord_detail.html'

class BordCreateView(CreateView):
    model = Bord
    template_name = 'bord/bord_create.html'
    form_class = BordForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super(BordCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(BordCreateView, self).get_context_data(**kwargs)
        context['check'] = self.kwargs['check']
        return context

class BordUpdateView(UpdateView):
    model = Bord
    form_class = BordForm
    template_name = 'bord/bord_update.html'

class BordDeleteView(DeleteView):
    model = Bord
    template_name = 'bord/bord_delete_confirm.html'

    def delete(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        obj = Bord.objects.get(pk=pk)
        obj.delete()
        return HttpResponseRedirect(reverse('bord:list', kwargs={'check': obj.check}))

contact/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView

# Create your views here.
from .models import Contact
from .forms import ContactForm

class ContactCreateView(CreateView):
    model = Contact
    template_name = 'base.html'
    success_url = '/contact/done'
    form_class = ContactForm

class ContactDoneView(TemplateView):
    template_name = 'contact_done.html'

source/views.py
from django.views.generic import View
from django.shortcuts import render
from django.views.generic import TemplateView , CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

class Home(View):
    def get(self, request ,*args, **kwargs):
        # context = {
        # }
        return render( request , "home.html", { } )

class Bord(View):
    def get(self, request,*args, **kwargs):
        return render( request,"bord.html" , {} )

class UsercreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneView(TemplateView):
    template_name = 'registration/register_done.html'

templates/bord/bord_confirm_delete.html
{% extends "base.html" %}


{% block content %}

<br><br>


    <form method="post" action="">
        {% csrf_token %}
        <p class="h2">죵말 삭제하시겠습니깕?</p>
        <br><br>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'bord-detail' object.id %}" class="btn btn-secondary" role="button">Cancel</a>
    </form>

{% endblock %}

templates/bord/bord_create.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Board {{ check }}</h2>

{% if form.errors %}
  {{ form.errors }}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
              <input type="hidden" name="check" value="{{check}}" >
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀 입력" required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <input type="file" id="id_image" name="image" >
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_description" name="description"></textarea>
                </div>
              </div>
                    <div class="form-group row">
                <label for="id_embed_code" class="col-sm-2 col-form-label">영상 링크</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_embed_code" name="embed_code"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Add</button>
                  <a href="{% url 'bord:list' check %}" class="btn btn-secondary" role="button">List</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord/bord_delete_confirm.html
{% extends 'base.html' %}

{% block content %}

<br><br>

<form method="post" action="">
    {% csrf_token %}
    <p class="h2">정말 이럴겁니까? 이게 최선입니까?</p>
    <br><br>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'bord:detail' object.id %}" class="btn btn-secondary" role="button">Cancel</a>
</form>

{% endblock %}

templates/bord/bord_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="email" class="form-control" id="inputEmail3" value="{{ object.title }}" disabled>
                </div>
              </div>
<!--              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">-->
                  <img src="{{ object.image.url }}" class="img-fluid" >
<!--                </div>
              </div>-->
<!--              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Video</label>
                <div class="col-sm-8">-->
                  {{ object.embed_code|safe }}
<!--                </div>
              </div>-->
    <!--          <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">-->
                  <textarea class="form-control" rows="3" disabled>{{object.description}}</textarea>
<!--                </div>
              </div>-->
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  {% if user.is_active %}
                  <a href="{% url 'bord:update' object.pk %}" class="btn btn-primary" role="button">Update</a>
                  <a href="{% url 'bord:delete' object.pk %}" class="btn btn-danger" role="button">Delete</a>
                  {% endif %}
                  <a href="{% url 'bord:list' object.check %}" class="btn btn-secondary" role="button">List</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock content %}

templates/bord/bord_list.html
{% extends 'base.html' %}

{% block content %}

    {% if check == "1" %}맨시티
    {% elif check == "2" %} 맨유
    {% elif check == "3" %} 첼시
    {% elif check == "4" %} 리버풀
    {% elif check == "5" %} 아스날
    {% elif check == "6" %} 번리
    {% elif check == "7" %} 토트넘
    {% elif check == "8" %} 레스터
    {% elif check == "9" %} 에버턴
    {% elif check == "10" %} 왓포드
    {% elif check == "11" %} 허더즈필드
    {% elif check == "12" %} 사우스샘프턴
    {% elif check == "13" %} 브라이튼
    {% elif check == "14" %} 크리스탈
    {% elif check == "15" %} 웨스트햄
    {% elif check == "16" %} 본머스
    {% elif check == "17" %} 스토크시티
    {% elif check == "18" %} 뉴캐슬
    {% elif check == "19" %} 웨스트브롬
    {% elif check == "20" %} 스완지
    {% endif %}

</h2>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Image</th>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter}}</th>
                        <td><a href="{{ item.get_absolute_url }}">{{ item.title}}</a></td>
                        <td><img class="img-fluid img-thumbnail" src="{{item.image.url}}" width="100px" height="100px"> </td>
                        <td>{{ item.user.username }}</td>
                        <td>{{ item.timestamp|date:"Y-m-d" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if user.is_active %}
    <div class="row">
        <div class="col-md-12 text-center">
              <a href="{% url 'bord:create' check %}" class="btn btn-primary" role="button">Add</a>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-12 text-center">
<!--
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/bord?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/bord?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}

 -->
  {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/board/check/{{check}}/?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/board/check/{{check}}/?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}




        </div>
    </div>


</div>

{% endblock %}

templates/bord/bord_update.html
{% extends 'base.html' %}

{% block content %}
<h2>Photo Update </h2>

{% if form.errors %}
  {{ form.errors }}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
              <input type="hidden" name="check" value="{{ object.check}}">
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" value="{{ object.title }}"
                         required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <img class="img-fluid" src="{{ object.image.url}}">
                  <input type="file" id="id_image" name="image" >
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_description" name="description">{{object.description}}</textarea>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_embed_code" class="col-sm-2 col-form-label">영상 링크</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_embed_code" name="embed_code">{{object.embed_code}}</textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="{% url 'bord:list' object.check %}" class="btn btn-secondary" role="button">Photo</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord1/bord_create.html
{% extends 'base.html' %}

{% block content %}

<h2>게시글 작성</h2>
{% if form.errors %}
  {{ form.errors }}
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀 입력" required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <input type="file" id="id_image" name="image">
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="bord-control" rows="3" id="id_description" name="description"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="{% url 'bord:list' %}" class="btn btn-secondary" role="button">Board</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord1/bord_detail.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="email" class="form-control" id="inputEmail3" value="{{ object.title }}" disabled>
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <img src="{{ object.image.url }}" class="img-fluid" >
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" disabled>{{object.description}}</textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  {% if user.is_active %}
                  <a href="{% url 'photo:update' object.pk %}" class="btn btn-primary" role="button">Update</a>
                  <a href="{% url 'photo:delete' object.pk %}" class="btn btn-danger" role="button">Delete</a>
                  <a id="delete_btn" href="{% url 'photo:delete_ajax' object.pk %}" class="btn btn-danger"
                     role="button">Delete_Ajax</a>
                  {% endif %}
                  <a href="{% url 'photo:list' %}" class="btn btn-secondary" role="button">Photo</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord1/bord_list1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    나와라 두번째 게시판
</body>
</html>

templates/bord1/bord_update.html
{% extends 'base.html' %}

{% block content %}
<h2>Photo Update </h2>

{% if form.errors %}
  {{ form.errors }}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" value="{{ object.title }}"
                         required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <img class="img-fluid" src="{{ object.image.url}}">
                  <input type="file" id="id_image" name="image" >
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_description" name="description">{{object.description}}</textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="{% url 'photo:list' %}" class="btn btn-secondary" role="button">Photo</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord121/bord_confirm_delete.html
{% extends "base.html" %}


{% block content %}

<br><br>


    <form method="post" action="">
        {% csrf_token %}
        <p class="h2">죵말 삭제하시겠습니깕?</p>
        <br><br>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'bord:detail' object.id %}" class="btn btn-secondary" role="button">Cancel</a>
    </form>

{% endblock %}

templates/bord121/bord_create.html
{% extends 'base.html' %}

{% block content %}

<h2>게시글 작성</h2>
{% if form.errors %}
  {{ form.errors }}
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}

              <input type="hidden" name="check" value="1" > <!--밸류값으로 게시판 구분-->
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀 입력" required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <input type="file" id="id_image" name="image">
                </div>
              </div>
              <div class="form-group row">
                  <label for="id_embed_code" class="col-sm-2 col-from-label">embed_code</label>
                <div class="col-sm-8">
                  <textarea class="bord-control" rows="5" id="id_embed_code" name="embed_code"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="bord-control" rows="5" id="id_description" name="description"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="{% url 'bord:list' %}" class="btn btn-secondary" role="button">Board</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/bord121/bord_delete.html
{% extends "base.html" %}


{% block content %}

<br><br>


    <form method="post" action="">
        {% csrf_token %}
        <p class="h2">이게 최선입니까? 다른방법은 없었던 겁니까..?</p>
        <br><br>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'bord:detail' object.id %}" class="btn btn-secondary" role="button">Cancel</a>
    </form>

{% endblock %}

templates/bord121/bord_detail.html
{% extends "base.html" %}

{% block content %}

<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-2" style="margin-left:50px;"></div>
        <div class="col-md-7 text-center">

        {{ object.title}} <br>
            <img src={{ object.image.url }}>
        {{ object.embed_code|safe }}
            <div class="col-sm-12">
                  <textarea class="form-control" rows="3" id="id_description" name="description" disabled>{{object.description}}</textarea>
            </div>

            <br><br>
            <a href="{% url 'bord:update' object.id %}" class="btn btn-primary" role="button">Update</a>
            <a href="{% url 'bord:delete' object.id %}" class="btn btn-danger" role="button">Delete</a>
            <br><br>
            <a href="javascript:history.back()" class="btn btn-secondary" role="button" >Back</a>

        </div>
    </div>

</div>


{% endblock %}

templates/bord121/bord_form.html
{% extends 'base.html' %}

    {% block content %}


<br><br>

<form method="post" action="">
    {% csrf_token %}
  <div class="form-group row">
    <label for="id_title" class="col-sm-2 col-form-label">Title:</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀을 입력하세요">
    </div>
  </div>
  <div class="form-group row">
    <label for="id_embed_code" class="col-sm-2 col-form-label">Embed code:</label>
    <div class="col-sm-8">
        <textarea cols="40" class="form-control" id="1d_embed_code" name="embed_code" rows="4"
                  placeholder="비디오 경로를 입력하세요" required></textarea>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10 text-center">
      <button type="submit" class="btn btn-primary">OK</button>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button" >Back</a>
    </div>
  </div>
</form>

    {% endblock %}

templates/bord121/bord_list.html
{% extends "base.html" %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">

      <br>

<br><br>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <!--<th scope="col" class="text-center">비디오 1</th>-->
      <!--<th scope="col" class="text-center">비디오 2</th>-->
      <!--<th scope="col" class="text-center">비디오 3</th>-->
      <th colspan="4" scope="col" class="text-center">
         <h2 class="text-center">Board
              {% if check == "1" %}1 : 기초
              {% elif check == "2" %} 2 : 중간
              {% endif %}

          </h2>
      </th>
    </tr>
  </thead>
  <tbody>

    {% for object in object_list %}

            <tr>
              <!--{{object.embed_code|safe}} <br>-->
                <td><a href="{% url 'bord:detail' object.id %}">{{object.title}}</a></td>
                <td>{{object.timestamp|date:"Y-m-d (H:i:s)[f:s]" }}</td>
                <td><a href="{% url 'bord:update' object.id %}" class="btn btn-primary" role="button">Update</a></td>
                <td><a href="{% url 'bord:delete' object.id %}" class="btn btn-danger" role="button">Delete</a></td>
            </tr>

    {% endfor %}
  </tbody>
</table>








    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <a href="{% url 'bord:create' check %}" class="btn btn-primary" role="button">게시물 작성</a>
    </div>
  </div>
</div>
{% endblock %}}

templates/bord121/bord_update.html
{% extends 'base.html' %}

{% block content %}

<h2>Bord Update </h2>

{% if form.errors %}
  {{ form.errors }}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-10">

            <form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
              <input type="hidden" name="check" value="{{ object.check}}">
              <div class="form-group row">
                <label for="id_title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="id_title" name="title" value="{{ object.title }}"
                         required>
                </div>
              </div>
              <div class="form-group row">
                <label for="id_image" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-6">
                  <img class="img-fluid" src="{{ object.image.url}}">
                  <input type="file" id="id_image" name="image" >
                </div>
              </div>
              <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-8">
                  <textarea class="form-control" rows="3" id="id_description" name="description">{{object.description}}</textarea>
                </div>
              </div>
                <div class="form-group row">
                  <label for="id_embed_code" class="col-sm-2 col-from-label">embed_code</label>
                <div class="col-sm-8">
                  <textarea class="bord-control" rows="5" id="id_embed_code" name="embed_code">{{ object.embed_code }}</textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-8 text-center">
                  <button type="submit" class="btn btn-primary">Update</button>
                  <a href="javascript:history.back()" class="btn btn-primary" role="button" >Cancel</a>
                  <a href="{% url 'bord:list' %}" class="btn btn-secondary" role="button">Board</a>
                </div>
              </div>
            </form>


        </div>
    </div>
</div>

{% endblock %}

templates/contact_done.html
{% extends 'base.html' %}

{% block content %}


<br><br><br>


<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <h1>메시지가 접수됐습니다.</h1>
            <p><a href="/" class="btn btn-secondary" role="button">Home</a></p>

        </div>
    </div>
</div>

{% endblock %}